debug: true
server:
  port: 8080

auth0:
  audience: https://e-commerce/api/v1
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-dplo3lsd.eu.auth0.com/